## **IMPORT LIBRARY**

In [1]:
import tensorflow as tf

## **Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor**

In [2]:
random_tensor = tf.random.normal([5,5],mean=0,stddev=1,seed=1)

random_tensor.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

## **Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor**

In [17]:
prima = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]
prime_tensor = tf.convert_to_tensor(prima, dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

## **Tampilkan dimensi dari kedua variable tersebut**

In [18]:
# Dimensi kedua Variabel
print(random_tensor.shape)
print(prime_tensor.shape)

(5, 5)
(5, 5)


## **Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)**

**Penjumlahan**

In [19]:
tf.add(random_tensor,prime_tensor).numpy()

array([[ 1.1886818,  4.4845986,  5.0653296,  4.557296 , 11.099248 ],
       [13.591225 , 17.592823 , 16.877071 , 22.277103 , 28.94373  ],
       [31.643545 , 36.735676 , 42.856632 , 43.56784  , 46.617165 ],
       [51.514656 , 60.261772 , 60.974693 , 66.73537  , 72.532814 ],
       [71.25702  , 78.5621   , 82.43399  , 89.32067  , 98.13283  ]],
      dtype=float32)

**Perkalian** 

In [20]:
tf.multiply(random_tensor,prime_tensor).numpy()

array([[  -1.6226364 ,    4.4537964 ,    0.32664686,  -17.09893   ,
           1.0917324 ],
       [   7.685916  ,   10.077991  ,  -40.335663  ,  -16.626637  ,
          -1.6318411 ],
       [  19.949888  ,   -9.77999   ,   76.12196   ,   24.417194  ,
         -17.993286  ],
       [ -78.7232    ,   74.444496  ,   -1.5436709 ,  -17.73019   ,
         108.82978   ],
       [-127.237335  ,  -34.593544  ,  -46.97883   ,   28.539564  ,
         109.884605  ]], dtype=float32)

**Pembagian**

In [21]:
tf.divide(random_tensor,prime_tensor).numpy()

array([[-4.0565911e-01,  4.9486625e-01,  1.3065875e-02, -3.4895775e-01,
         9.0225823e-03],
       [ 4.5478795e-02,  3.4871940e-02, -1.1173314e-01, -3.1430315e-02,
        -1.9403580e-03],
       [ 2.0759510e-02, -7.1438937e-03,  4.5283735e-02,  1.3205621e-02,
        -8.1454450e-03],
       [-2.8025346e-02,  2.1385951e-02, -4.1485377e-04, -3.9496967e-03,
         2.1588927e-02],
       [-2.3876399e-02, -5.5429488e-03, -6.8193977e-03,  3.6030253e-03,
         1.1678670e-02]], dtype=float32)

**Pembagian**

In [22]:
tf.pow(random_tensor, prime_tensor).numpy()

array([[ 6.5823728e-01,  3.2721055e+00,  1.1899876e-06, -5.1891492e+02,
         9.2036214e-12],
       [ 1.0783996e-03,  1.3795117e-04, -1.6284565e+06, -5.7380047e-04,
        -5.7294839e-37],
       [ 1.1639711e-06, -4.1596646e-22,  1.0417667e+11,  2.7025481e-11,
        -2.5211261e-20],
       [-1.2788605e+09,  9.0751462e+05,  0.0000000e+00,  0.0000000e+00,
         1.4782479e+13],
       [-4.1142766e+17, -4.6565877e-29, -3.0507073e-21,  0.0000000e+00,
         1.7948009e+05]], dtype=float32)

**Logaritma**

In [23]:
tf.math.log(random_tensor, prime_tensor).numpy()

array([[        nan,  0.39514455, -2.7283134 ,         nan, -2.3101294 ],
       [-0.5255598 , -0.52285945,         nan,         nan,         nan],
       [-0.44076362,         nan,  0.61876476, -0.5659126 ,         nan],
       [        nan,  0.23251635,         nan,         nan,  0.42710513],
       [        nan,         nan,         nan, -1.1373451 ,  0.12471979]],
      dtype=float32)

## **Tampilkan nilai maksimal dan minimal dari variable random_tensor**

In [24]:
tf.argmax(random_tensor, axis=0).numpy()

array([2, 0, 2, 2, 3])

In [25]:
tf.argmin(random_tensor, axis=0).numpy()

array([4, 4, 1, 0, 2])

## **Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)**

In [26]:
#sebelum
print(f"Size original : {random_tensor.shape} {prime_tensor.shape}")

Size original : (5, 5) (5, 5)


In [27]:
# gabungkan kedua sample
concat_sample = tf.concat([random_tensor, prime_tensor], axis=0)
print(f"Size data yang sudah di concat : {concat_sample.shape}")

Size data yang sudah di concat : (10, 5)


## **Tampilkan hasil sorting dari kedua variable di atas. (descending)**

In [28]:
print(tf.sort(random_tensor, direction="DESCENDING"))

tf.Tensor(
[[ 1.4845988   0.0992484   0.06532937 -0.8113182  -2.4427042 ]
 [ 0.59282297  0.5912243  -0.05627038 -0.72289723 -2.1229296 ]
 [ 1.8566332   0.6435448   0.5678417  -0.26432407 -0.3828359 ]
 [ 1.5328138   1.2617711  -0.02530608 -0.2646297  -1.4853433 ]
 [ 1.132831    0.32066926 -0.43789294 -0.56601    -1.7429771 ]], shape=(5, 5), dtype=float32)


In [29]:
print(tf.sort(prime_tensor, direction="DESCENDING"))

tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
